- name: This playbook will install nginx, configures the web root folder, deploys custom web page
  hosts: ubuntu  
  vars:
  - greeting_msg: Welcome to DevOps !!
  - provisioner_tool: Docker
  - conf_mgr_tool: Ansible
  tasks:
  - name: Install nginx in Ubuntu ansible nodes
    when: ansible_distribution == "Ubuntu"
    apt: name=nginx state=latest update_cache=yes

  - name: Install nginx in RHEL ansible nodes
    when: ansible_distribution == "RedHat"
    yum: name=nginx state=latest

  - name: Start nginx service in Ubuntu ansible nodes
    when: ansible_distribution == "Ubuntu"
    shell: service nginx start

  - name: Start nginx service in RHEL ansible nodes
    when: ansible_distribution == "RedHat"
    service: name=nginx state=started

  - name: Disable firewall in RHEL
    when: ansible_distribution == "RedHat"
    service: name=firewalld state=stopped

  - name: Create the custom web root folder
    file: path=/var/html state=directory mode=0755

  - name: Retrieve IP address
    shell: hostname -i
    register: ipaddress

  - debug: var=ipaddress

  - name: Deploy custom web page
    template: src=index.html.j2 dest=/var/html/index.html

  - name: Configure nginx web root folder to pick html pages from our custom folder in Ubuntu
    when: ansible_distribution == "Ubuntu"
    copy: src=default dest=/etc/nginx/sites-available/default

  - name: Configure nginx web root folder to pick html pages from our custom folder in RHEL 
    when: ansible_distribution == "RedHat"
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf

  - name: Restart nginx service in Ubuntu ansible nodes
    when: ansible_distribution == "Ubuntu"
    shell: service nginx restart

  - name: Restart nginx service in RHEL ansible nodes
    when: ansible_distribution == "RedHat"
    service: name=nginx state=restarted

      #- name: Test web page access
      #hosts: localhost
      #vars:
      #urls:
      #- http://192.168.1.99:8001
      #- http://192.168.1.99:8002
      # tasks:
      #- name: Curl webpage
      #shell: "curl {{item}}"
      #with_list: "{{urls}}"
      #register: output

      #- debug: var=output
