- name: Provision docker containers in local machine
  hosts: localhost
  vars:
  - env:
      ANSIBLE_CONFIG: ./ansible.cfg
  tasks:
  - shell: 
      cmd: echo "" > ~/.ssh/known_hosts
      executable: /bin/bash
    ignore_errors: yes

  - shell: ansible-playbook provision-ansible-nodes-playbook.yml
    environment: "{{env}}"
    become: yes

- name: This play run in Ubuntu and CentOS ansible nodes
  hosts: all 
  tasks:
  - debug: var=ansible_distribution
