- name: Provision docker containers in local machine
  hosts: localhost
  become: yes
  tasks:
  - shell: ansible-playbook -i ./inventory provision-ansible-nodes-playbook.yml

- name: This play run in Ubuntu and CentOS ansible nodes
  hosts: all 
  tasks:
  - debug: var=ansible_distribution
